<?php

namespace Acme\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoicesRepository extends EntityRepository
{

	//repository function to fetch data relative in invoice and invoicelineitems tables.  
	public function getAllInvoicesByClients($clientId, $datefilter){
		//Last Month to date
		if($datefilter == "1") {
			$dtm = date('m');
			$dtlm = $dtm-1;
			$dtlm = date('m',$dtlm);
			$dtlastmonth = date('Y')."-".$dtlm."-01";
			
			$sql = 'SELECT * FROM invoices 
					INNER JOIN invoicelineitems ON invoices.invoice_num = invoicelineitems.invoice_num 
					INNER JOIN products ON invoicelineitems.product_id = products.product_id
					WHERE invoices.client_id LIKE :id AND invoices.invoice_date BETWEEN "'.$dtlastmonth.'" AND "'.date('Y-m-j').'"';
					
		} // This Month
		else if($datefilter == "2") {
			
			$sql = 'SELECT * FROM invoices 
					INNER JOIN invoicelineitems ON invoices.invoice_num = invoicelineitems.invoice_num 
					INNER JOIN products ON invoicelineitems.product_id = products.product_id
					WHERE invoices.client_id LIKE :id AND invoices.invoice_date BETWEEN "'.date('Y').'-'.date('m').'-01'.'" AND "'.date('Y-m-j').'"';
					
		} // This Year
		else if($datefilter == "3") {
			
			$sql = 'SELECT * FROM invoices 
					INNER JOIN invoicelineitems ON invoices.invoice_num = invoicelineitems.invoice_num 
					INNER JOIN products ON invoicelineitems.product_id = products.product_id
					WHERE invoices.client_id LIKE :id AND invoices.invoice_date BETWEEN "'.date('Y').'-01'.'-01'.'" AND "'.date('Y').'-12'.'-31'.'"';
		}// Last Year
		else if($datefilter == "4") {
			$dty = date('Y');
			$dtly = $dty-1;
			
			$dtlastyear = $dtly."-01"."-01";
			
			$lastmonthtodate = '';
			$sql = 'SELECT * FROM invoices 
					INNER JOIN invoicelineitems ON invoices.invoice_num = invoicelineitems.invoice_num 
					INNER JOIN products ON invoicelineitems.product_id = products.product_id
					WHERE invoices.client_id LIKE :id AND invoices.invoice_date BETWEEN "'.$dtlastyear.'" AND "'.$dtly.'-12'.'-31'.'"';
		} //Default
		else {
			$sql = 'SELECT * FROM invoices 
					INNER JOIN invoicelineitems ON invoices.invoice_num = invoicelineitems.invoice_num 
					INNER JOIN products ON invoicelineitems.product_id = products.product_id
					WHERE invoices.client_id LIKE :id AND invoices.invoice_date';
		}
		$params = array(
		'id' => '%'.$clientId.'%',
		);

	return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
	}
}
